#!/bin/bash

# A manager of my computing environment.

set -eu

THIS_DIR="${PWD}"
THIS_SCRIPT=$(basename "${BASH_SOURCE[0]}")

NIXPKGS="${THIS_DIR}/nixpkgs"
SCRIPTS="${THIS_DIR}/scripts/include"

log() {
  echo "[${THIS_SCRIPT}] " "$@" >&2
}

usage() {
  cat <<EOF
Manage my computing environment

USAGE:
  ${THIS_SCRIPT} [OPTION] COMMAND

OPTION:
  -h                      Show this message

COMMAND:
  nix                     Install nix and home-manager (imperative)
  home                    Install packages with home-manager
  ocaml                   Install OCaml toolchain (imperative)
  rust                    Install Rust toolchains managed by Rustup (imperative)
  vscode                  Re-generate VSCode market extensions manifest
EOF
}

command=""

parse_args() {
  while getopts "h" opt; do
    case "${opt}" in
    h)
      usage
      exit 0
      ;;
    *)
      log "Please, provide a valid option other than '${opt}'"
      exit 64
      ;;
    esac
  done

  shift $((OPTIND - 1))

  if [[ $# -ne 1 ]]; then
    log "Please, provide some command"
    exit 64
  fi

  command="$1"
}

nix() {
  log "Installing nix & home-manager"

  curl -L https://nixos.org/nix/install | sh

  nix-channel --add https://github.com/nix-community/home-manager/archive/release-20.09.tar.gz home-manager
  nix-channel --update

  nix-shell '<home-manager>' -A install
}

home() {
  local source="${NIXPKGS}"
  local target="${HOME}/.config"

  if [[ ! -d "${source}" ]]; then
    echo "Please, check whether '${source}' actually exists"
    exit 66
  fi

  log "Instaling '${source}' to '${target}'"

  mkdir -p "${target}"
  ln -sf "${source}" "${target}"

  log "Switching home-manager"

  home-manager switch
}

ocaml() {
  log "Installing OCaml utilities"

  opam init
  opam install dune
}

rust() {
  log "Installing Rust utilities"

  rustup default stable
  rustup update
  rustup component add \
    rust-src
  rustup toolchain install nightly
}

vscode() {
  log "Re-generating VSCode market extensions manifest"

  "${SCRIPTS}/vscode/generate_market_extensions"
}

handle() {
  local command="$1"

  case "${command}" in
  "nix")
    nix
    ;;
  "home")
    home
    ;;
  "ocaml")
    ocaml
    ;;
  "rust")
    rust
    ;;
  "vscode")
    vscode
    ;;
  *)
    log "Please, provide a valid command other than '${command}'"
    exit 64
    ;;
  esac
}

main() {
  parse_args "$@"

  handle "${command}"

  log "Done"
}

main "$@"
