# This file was auto-generated by: "generate_market_extensions".
{ extensionFromVscodeMarketplace }: [
  (extensionFromVscodeMarketplace {
    publisher = "aaron-bond";
    name = "better-comments";
    version = "3.0.2";
    sha256 = "15w1ixvp6vn9ng6mmcmv9ch0ngx8m85i1yabxdfn6zx3ypq802c5";
  })
  (extensionFromVscodeMarketplace {
    publisher = "ArashSahebolamri";
    name = "alloy";
    version = "0.7.1";
    sha256 = "00qm8rg0bbkmrvwrx13v68ninn8d4dm57m1j5f5p8r0344wcbwdj";
  })
  (extensionFromVscodeMarketplace {
    publisher = "arrterian";
    name = "nix-env-selector";
    version = "1.0.9";
    sha256 = "0kdfhkdkffr3cdxmj7llb9g3wqpm13ml75rpkwlg1y0pkxcnlk2f";
  })
  (extensionFromVscodeMarketplace {
    publisher = "azemoh";
    name = "one-monokai";
    version = "0.5.0";
    sha256 = "1rqg3np6jc9lrl9xqq8iq74y4ag3wnj5c0zv9h9ljpk5xzp4rdva";
  })
  (extensionFromVscodeMarketplace {
    publisher = "castwide";
    name = "solargraph";
    version = "0.23.0";
    sha256 = "0ivawyq16712j2q4wic3y42lbqfml5gs24glvlglpi0kcgnii96n";
  })
  (extensionFromVscodeMarketplace {
    publisher = "connorshea";
    name = "vscode-ruby-test-adapter";
    version = "0.9.1";
    sha256 = "10jfrs7yf9nnmggzjvhhgf1n16xv74a6bz5fkl95i9x11zv04qzi";
  })
  (extensionFromVscodeMarketplace {
    publisher = "cschlosser";
    name = "doxdocgen";
    version = "1.4.0";
    sha256 = "1d95znf2vsdzv9jqiigh9zm62dp4m9jz3qcfaxn0n0pvalbiyw92";
  })
  (extensionFromVscodeMarketplace {
    publisher = "dongyuzhao";
    name = "alloy-vscode";
    version = "0.1.6";
    sha256 = "1yyckiyf7ki6f951xij8i22zwkhb9hxaix36558qjwivqs6330y1";
  })
  (extensionFromVscodeMarketplace {
    publisher = "dorzey";
    name = "vscode-sqlfluff";
    version = "0.1.2";
    sha256 = "193hric4qp92jgpq5m53sgip7c589hncrmkrd0jbn1c2qyhgn11x";
  })
  (extensionFromVscodeMarketplace {
    publisher = "exiasr";
    name = "hadolint";
    version = "1.1.2";
    sha256 = "00x6bnjm0yk0fcw91c47g8c5shgbcvxyyz49r4y23q4gqizvaqz8";
  })
  (extensionFromVscodeMarketplace {
    publisher = "formulahendry";
    name = "terminal";
    version = "0.0.10";
    sha256 = "0gj71xy7r82n1pic00xsi04dg7zg0dsxx000s03iq6lnz47s84gn";
  })
  (extensionFromVscodeMarketplace {
    publisher = "fwcd";
    name = "kotlin";
    version = "0.2.26";
    sha256 = "1br0vr4v1xcl4c7bcqwzfqd4xr6q2ajwkipqrwm928mj96dkafkn";
  })
  (extensionFromVscodeMarketplace {
    publisher = "jcanero";
    name = "hoogle-vscode";
    version = "0.0.7";
    sha256 = "0ndapfrv3j82792hws7b3zki76m2s1bfh9dss1xjgcal1aqajka1";
  })
  (extensionFromVscodeMarketplace {
    publisher = "jebbs";
    name = "plantuml";
    version = "2.17.4";
    sha256 = "1s6jp1rx1k03ir7j3fsyqkhnnp9m6akabznb4pmjxpkvn2wzlz3y";
  })
  (extensionFromVscodeMarketplace {
    publisher = "joaompinto";
    name = "vscode-graphviz";
    version = "0.0.6";
    sha256 = "17z5zgr8l94mj8dgqxwsrpixnkz0778fp1g4rxc7i56wb1zbik3w";
  })
  (extensionFromVscodeMarketplace {
    publisher = "kaiwood";
    name = "endwise";
    version = "1.5.1";
    sha256 = "1dg096dnv3isyimp3r73ih25ya0yj0m1y9ryzrz40m0mbsk21mp4";
  })
  (extensionFromVscodeMarketplace {
    publisher = "leanprover";
    name = "lean4";
    version = "0.0.95";
    sha256 = "09d3sk6kp8v37fzary9q31wv24mabv9n20p2pg4cl2bb8is67ck6";
  })
  (extensionFromVscodeMarketplace {
    publisher = "lucax88x";
    name = "codeacejumper";
    version = "3.3.2";
    sha256 = "02a5f0lg0rmrjjf52z30mk19ii71pcdxjmbcb4v6haw1pkm6anqn";
  })
  (extensionFromVscodeMarketplace {
    publisher = "mattn";
    name = "lisp";
    version = "0.1.12";
    sha256 = "0k10d77ffl6ybmk7mrpmlsawzwppp87aix2a2i24jq7lqnnqb9n7";
  })
  (extensionFromVscodeMarketplace {
    publisher = "maximedenes";
    name = "vscoq";
    version = "0.3.6";
    sha256 = "1sailpizg7zvncggdma9dyxdnga8jya1a2vswwij1rzd9il04j3g";
  })
  (extensionFromVscodeMarketplace {
    publisher = "meraymond";
    name = "idris-vscode";
    version = "0.0.13";
    sha256 = "1h4zf1k5586vngb2ibwn46l0jv2cgjx50sa7w63msvwxcvsqyn2i";
  })
  (extensionFromVscodeMarketplace {
    publisher = "ms-vscode";
    name = "cmake-tools";
    version = "1.13.7";
    sha256 = "037rssnzgfxskbx6id13yzpg1q7rd3w1k2ivb33bm9wsnxqka3dz";
  })
  (extensionFromVscodeMarketplace {
    publisher = "ms-vscode";
    name = "makefile-tools";
    version = "0.6.0";
    sha256 = "07zagq5ib9hd3w67yk2g728vypr4qazw0g9dyd5bax21shnmppa9";
  })
  (extensionFromVscodeMarketplace {
    publisher = "ms-vscode";
    name = "test-adapter-converter";
    version = "0.1.6";
    sha256 = "0pj4ln8g8dzri766h9grdvhknz2mdzwv0lmzkpy7l9w9xx8jsbsh";
  })
  (extensionFromVscodeMarketplace {
    publisher = "mtxr";
    name = "sqltools";
    version = "0.25.1";
    sha256 = "1zawd80w0slyagm9m72dsr3ckh4fwf4as4a71iy8pw5pk22cwbxa";
  })
  (extensionFromVscodeMarketplace {
    publisher = "mtxr";
    name = "sqltools-driver-mysql";
    version = "0.4.0";
    sha256 = "0mqjyx6wgn6rp4y3v2y6fbhb78w5fry5l19nwkqnm5s1kwdzq9vr";
  })
  (extensionFromVscodeMarketplace {
    publisher = "mtxr";
    name = "sqltools-driver-pg";
    version = "0.3.0";
    sha256 = "1addlwvayxgfg8slnmnrw8gv1bgwh059ax38zyh59m808y1zi7ia";
  })
  (extensionFromVscodeMarketplace {
    publisher = "naco-siren";
    name = "gradle-language";
    version = "0.2.3";
    sha256 = "15lzxvym0mkljjn57av1p4z6hqqwbsbn5idw2fn7nccgrl93aywf";
  })
  (extensionFromVscodeMarketplace {
    publisher = "nicoespeon";
    name = "abracadabra";
    version = "6.15.3";
    sha256 = "1dj0m5cd7gzxv1zxiyvmvnhq42yi15pchi3sq76vdr3bpfj0iihz";
  })
  (extensionFromVscodeMarketplace {
    publisher = "notskm";
    name = "clang-tidy";
    version = "0.5.1";
    sha256 = "0z44hbrbzlhxbzf1j55xpl5fb7gic9avvcz4dvljrwz4qqdjzq4x";
  })
  (extensionFromVscodeMarketplace {
    publisher = "pivotal";
    name = "vscode-spring-boot";
    version = "1.39.0";
    sha256 = "09gb8crkh38zl9wcb762mp7n1yhlkhqc8ava2rv3xr2hfd5awwjw";
  })
  (extensionFromVscodeMarketplace {
    publisher = "rebornix";
    name = "Ruby";
    version = "0.28.1";
    sha256 = "179g7nc6mf5rkha75v7rmb3vl8x4zc6qk1m0wn4pgylkxnzis18w";
  })
  (extensionFromVscodeMarketplace {
    publisher = "redhat";
    name = "vscode-xml";
    version = "0.21.2022092404";
    sha256 = "0dckv4l385zwlajpv2xjzx69cv66ra6wznva7jqxfql5kj7sx8sr";
  })
  (extensionFromVscodeMarketplace {
    publisher = "Rubymaniac";
    name = "vscode-direnv";
    version = "0.0.2";
    sha256 = "1gml41bc77qlydnvk1rkaiv95rwprzqgj895kxllqy4ps8ly6nsd";
  })
  (extensionFromVscodeMarketplace {
    publisher = "ryanolsonx";
    name = "zenburn";
    version = "2.1.3";
    sha256 = "061syx9dj6bc7734sd7dnxbkhg5wz9qdpxy254rm9vn8nmj8mqf2";
  })
  (extensionFromVscodeMarketplace {
    publisher = "sjhuangx";
    name = "vscode-scheme";
    version = "0.4.0";
    sha256 = "07vjfymvfv98s5r5a4b5iqhgfz1wpgq2l8h3wlq1bnhhhvmq5pq4";
  })
  (extensionFromVscodeMarketplace {
    publisher = "twxs";
    name = "cmake";
    version = "0.0.17";
    sha256 = "11hzjd0gxkq37689rrr2aszxng5l9fwpgs9nnglq3zhfa1msyn08";
  })
  (extensionFromVscodeMarketplace {
    publisher = "vscjava";
    name = "vscode-java-debug";
    version = "0.44.2022092202";
    sha256 = "03ixs71w6jalxvadm9151i41d1cv67j2blak6vxf0l2k85z1ldqy";
  })
  (extensionFromVscodeMarketplace {
    publisher = "vscjava";
    name = "vscode-java-test";
    version = "0.37.2022090902";
    sha256 = "17i9jfwpjjxp81dg6nnviczzmr47pvz33zc4bwfvz69ckn6v74j4";
  })
  (extensionFromVscodeMarketplace {
    publisher = "vscjava";
    name = "vscode-spring-boot-dashboard";
    version = "0.7.2022090900";
    sha256 = "1qlnwyj4iwwwd0jvmai6wllnwx5ib000ccny96m688v6izrw6x4j";
  })
  (extensionFromVscodeMarketplace {
    publisher = "vscjava";
    name = "vscode-spring-initializr";
    version = "0.11.2022090703";
    sha256 = "0k2jf9px22l72a52hai47mz2w27hsa75hhl591wi9fspndsxrcq0";
  })
  (extensionFromVscodeMarketplace {
    publisher = "vscode-org-mode";
    name = "org-mode";
    version = "1.0.0";
    sha256 = "1dp6mz1rb8awrrpig1j8y6nyln0186gkmrflfr8hahaqr668il53";
  })
  (extensionFromVscodeMarketplace {
    publisher = "wayou";
    name = "vscode-todo-highlight";
    version = "1.0.5";
    sha256 = "1sg4zbr1jgj9adsj3rik5flcn6cbr4k2pzxi446rfzbzvcqns189";
  })
  (extensionFromVscodeMarketplace {
    publisher = "wingrunr21";
    name = "vscode-ruby";
    version = "0.28.0";
    sha256 = "1gab5cka87zw7i324rz9gmv423rf5sylsq1q1dhfkizmrpwzaxqz";
  })
  (extensionFromVscodeMarketplace {
    publisher = "wix";
    name = "glean";
    version = "5.2.2";
    sha256 = "0zicmdhphsyvbqsbabydfsr3gljmzjdixxqjk77qrfwjd2mzjh16";
  })
  (extensionFromVscodeMarketplace {
    publisher = "xabikos";
    name = "JavaScriptSnippets";
    version = "1.8.0";
    sha256 = "19xg24alxsvq8pvafprshg7qxzx8p37bzk7qz6kjgkpvandrdpl6";
  })
]
