# This file was auto-generated by: "generate_market_extensions".
{ extensionFromVscodeMarketplace }: [
  (extensionFromVscodeMarketplace {
    publisher = "aaron-bond";
    name = "better-comments";
    version = "3.0.2";
    sha256 = "15w1ixvp6vn9ng6mmcmv9ch0ngx8m85i1yabxdfn6zx3ypq802c5";
  })
  (extensionFromVscodeMarketplace {
    publisher = "ArashSahebolamri";
    name = "alloy";
    version = "0.7.1";
    sha256 = "00qm8rg0bbkmrvwrx13v68ninn8d4dm57m1j5f5p8r0344wcbwdj";
  })
  (extensionFromVscodeMarketplace {
    publisher = "arrterian";
    name = "nix-env-selector";
    version = "1.0.9";
    sha256 = "0kdfhkdkffr3cdxmj7llb9g3wqpm13ml75rpkwlg1y0pkxcnlk2f";
  })
  (extensionFromVscodeMarketplace {
    publisher = "azemoh";
    name = "one-monokai";
    version = "0.5.0";
    sha256 = "1rqg3np6jc9lrl9xqq8iq74y4ag3wnj5c0zv9h9ljpk5xzp4rdva";
  })
  (extensionFromVscodeMarketplace {
    publisher = "castwide";
    name = "solargraph";
    version = "0.24.0";
    sha256 = "0pcd4gwzg4rla5mz6kj4dqq30pyvsv6290an15yr89wxwcvk6qzf";
  })
  (extensionFromVscodeMarketplace {
    publisher = "connorshea";
    name = "vscode-ruby-test-adapter";
    version = "0.9.2";
    sha256 = "04w99zfnhxaf2lxnag28sgjfhlfj55rrjalm63v2fsihj1d4hyk2";
  })
  (extensionFromVscodeMarketplace {
    publisher = "cschlosser";
    name = "doxdocgen";
    version = "1.4.0";
    sha256 = "1d95znf2vsdzv9jqiigh9zm62dp4m9jz3qcfaxn0n0pvalbiyw92";
  })
  (extensionFromVscodeMarketplace {
    publisher = "dongyuzhao";
    name = "alloy-vscode";
    version = "0.1.6";
    sha256 = "1yyckiyf7ki6f951xij8i22zwkhb9hxaix36558qjwivqs6330y1";
  })
  (extensionFromVscodeMarketplace {
    publisher = "dorzey";
    name = "vscode-sqlfluff";
    version = "2.3.1";
    sha256 = "1gkrm7spw9y1d8w6703y86dm4ws13s25gz8xhnncm248xhyzx719";
  })
  (extensionFromVscodeMarketplace {
    publisher = "exiasr";
    name = "hadolint";
    version = "1.1.2";
    sha256 = "00x6bnjm0yk0fcw91c47g8c5shgbcvxyyz49r4y23q4gqizvaqz8";
  })
  (extensionFromVscodeMarketplace {
    publisher = "formulahendry";
    name = "terminal";
    version = "0.0.10";
    sha256 = "0gj71xy7r82n1pic00xsi04dg7zg0dsxx000s03iq6lnz47s84gn";
  })
  (extensionFromVscodeMarketplace {
    publisher = "fwcd";
    name = "kotlin";
    version = "0.2.31";
    sha256 = "1yngrbqndb7jccmakpjv98y8amffvk2zbj3dhz0khdxz6ym18vb3";
  })
  (extensionFromVscodeMarketplace {
    publisher = "jcanero";
    name = "hoogle-vscode";
    version = "0.0.7";
    sha256 = "0ndapfrv3j82792hws7b3zki76m2s1bfh9dss1xjgcal1aqajka1";
  })
  (extensionFromVscodeMarketplace {
    publisher = "jebbs";
    name = "plantuml";
    version = "2.17.5";
    sha256 = "0l0amipyf74bkyiksnqfy2qcvv3qsshk9bqqqx28fk06nvx1zy8b";
  })
  (extensionFromVscodeMarketplace {
    publisher = "joaompinto";
    name = "vscode-graphviz";
    version = "0.0.6";
    sha256 = "17z5zgr8l94mj8dgqxwsrpixnkz0778fp1g4rxc7i56wb1zbik3w";
  })
  (extensionFromVscodeMarketplace {
    publisher = "kaiwood";
    name = "endwise";
    version = "1.5.1";
    sha256 = "1dg096dnv3isyimp3r73ih25ya0yj0m1y9ryzrz40m0mbsk21mp4";
  })
  (extensionFromVscodeMarketplace {
    publisher = "leanprover";
    name = "lean4";
    version = "0.0.102";
    sha256 = "033afryfl53vnf89z1lac8adr11wginpd47abph9d6daxlpsaw3a";
  })
  (extensionFromVscodeMarketplace {
    publisher = "lucax88x";
    name = "codeacejumper";
    version = "3.3.2";
    sha256 = "02a5f0lg0rmrjjf52z30mk19ii71pcdxjmbcb4v6haw1pkm6anqn";
  })
  (extensionFromVscodeMarketplace {
    publisher = "mattn";
    name = "lisp";
    version = "0.1.12";
    sha256 = "0k10d77ffl6ybmk7mrpmlsawzwppp87aix2a2i24jq7lqnnqb9n7";
  })
  (extensionFromVscodeMarketplace {
    publisher = "maximedenes";
    name = "vscoq";
    version = "0.3.8";
    sha256 = "12qyvc0d1m0i5mxmjp1swq7sd6ch6yi9v0f14hz64lig3clgjmfh";
  })
  (extensionFromVscodeMarketplace {
    publisher = "meraymond";
    name = "idris-vscode";
    version = "0.0.14";
    sha256 = "0yam13n021lmc93m8rpw96ksci0jshfrlnnfdk1q9yqrxydy6320";
  })
  (extensionFromVscodeMarketplace {
    publisher = "ms-vscode";
    name = "cmake-tools";
    version = "1.15.8";
    sha256 = "135i7fjfv3i2qs240rrxszxd2b7ibzcrid713kj4fxmqq8nrs4ll";
  })
  (extensionFromVscodeMarketplace {
    publisher = "ms-vscode";
    name = "makefile-tools";
    version = "0.8.1";
    sha256 = "05swb85r4s589c0j0yff54zwy7f08735a3vwyz54im0f6y2wqajl";
  })
  (extensionFromVscodeMarketplace {
    publisher = "ms-vscode";
    name = "test-adapter-converter";
    version = "0.1.7";
    sha256 = "1rvdxkzf34cmqlz9a7f7x3zg4j7zd3kyjcdv5ycqx97hq9gp96sv";
  })
  (extensionFromVscodeMarketplace {
    publisher = "mtxr";
    name = "sqltools";
    version = "0.27.1";
    sha256 = "01bha7xcbad55lacxcrvvqdn5vcvhcw2h4jcbz42plrb3imlyy75";
  })
  (extensionFromVscodeMarketplace {
    publisher = "mtxr";
    name = "sqltools-driver-mysql";
    version = "0.5.1";
    sha256 = "1n4wpx3mj6gvim634k3gfffrj80w02jd06rg9kwx9zqnja7c4ls5";
  })
  (extensionFromVscodeMarketplace {
    publisher = "mtxr";
    name = "sqltools-driver-pg";
    version = "0.5.1";
    sha256 = "0b4z5ma7p3nb4nxvvqfv9y384z5l3ai2z55brild4zcs6hr4m7jd";
  })
  (extensionFromVscodeMarketplace {
    publisher = "naco-siren";
    name = "gradle-language";
    version = "0.2.3";
    sha256 = "15lzxvym0mkljjn57av1p4z6hqqwbsbn5idw2fn7nccgrl93aywf";
  })
  (extensionFromVscodeMarketplace {
    publisher = "nicoespeon";
    name = "abracadabra";
    version = "8.0.1";
    sha256 = "1mizqzyn9jdjvdvs44b2rcasrm8ybwdsq8fky4qq881dfmn2r0i3";
  })
  (extensionFromVscodeMarketplace {
    publisher = "notskm";
    name = "clang-tidy";
    version = "0.5.1";
    sha256 = "0z44hbrbzlhxbzf1j55xpl5fb7gic9avvcz4dvljrwz4qqdjzq4x";
  })
  (extensionFromVscodeMarketplace {
    publisher = "rebornix";
    name = "Ruby";
    version = "0.28.1";
    sha256 = "179g7nc6mf5rkha75v7rmb3vl8x4zc6qk1m0wn4pgylkxnzis18w";
  })
  (extensionFromVscodeMarketplace {
    publisher = "redhat";
    name = "vscode-xml";
    version = "0.25.2023050404";
    sha256 = "1jznfhxha8ci0scz7amzya8d8ddqc2sk3ighhqr7bawx61iym5lz";
  })
  (extensionFromVscodeMarketplace {
    publisher = "Rubymaniac";
    name = "vscode-direnv";
    version = "0.0.2";
    sha256 = "1gml41bc77qlydnvk1rkaiv95rwprzqgj895kxllqy4ps8ly6nsd";
  })
  (extensionFromVscodeMarketplace {
    publisher = "ryanolsonx";
    name = "zenburn";
    version = "2.1.4";
    sha256 = "0dzgdz6kkiyng8x8gxq6ljnfgkf6k8pgxq8f1awj9ich8jpx2zgm";
  })
  (extensionFromVscodeMarketplace {
    publisher = "sjhuangx";
    name = "vscode-scheme";
    version = "0.4.0";
    sha256 = "07vjfymvfv98s5r5a4b5iqhgfz1wpgq2l8h3wlq1bnhhhvmq5pq4";
  })
  (extensionFromVscodeMarketplace {
    publisher = "twxs";
    name = "cmake";
    version = "0.0.17";
    sha256 = "11hzjd0gxkq37689rrr2aszxng5l9fwpgs9nnglq3zhfa1msyn08";
  })
  (extensionFromVscodeMarketplace {
    publisher = "vmware";
    name = "vscode-spring-boot";
    version = "1.47.2023051104";
    sha256 = "1g7rddbv4pni0b4paqiim6i9s985vdg496bflnc4mn913x49c38k";
  })
  (extensionFromVscodeMarketplace {
    publisher = "vscjava";
    name = "vscode-java-debug";
    version = "0.50.2023042406";
    sha256 = "13dnbgayw2rym0rwz7nj9y2cspszgn9gl2zhw20lb3lq884misfz";
  })
  (extensionFromVscodeMarketplace {
    publisher = "vscjava";
    name = "vscode-java-test";
    version = "0.38.2023051002";
    sha256 = "0ml3pcpd6pjpbkkwdkkmr4vnfwl5z1870ikmbvr8frh5gsf88pap";
  })
  (extensionFromVscodeMarketplace {
    publisher = "vscjava";
    name = "vscode-spring-boot-dashboard";
    version = "0.13.2023051200";
    sha256 = "0sl5d4knkj9hzhd9zf06nr12r303h9qx9b2b65prmcmi4sf0rixm";
  })
  (extensionFromVscodeMarketplace {
    publisher = "vscjava";
    name = "vscode-spring-initializr";
    version = "0.11.2023041103";
    sha256 = "1w3gymv70j2541awqpn95wnhcdcxbc25s8iz68a02rq4l9ll0jb6";
  })
  (extensionFromVscodeMarketplace {
    publisher = "vscode-org-mode";
    name = "org-mode";
    version = "1.0.0";
    sha256 = "1dp6mz1rb8awrrpig1j8y6nyln0186gkmrflfr8hahaqr668il53";
  })
  (extensionFromVscodeMarketplace {
    publisher = "wayou";
    name = "vscode-todo-highlight";
    version = "1.0.5";
    sha256 = "1sg4zbr1jgj9adsj3rik5flcn6cbr4k2pzxi446rfzbzvcqns189";
  })
  (extensionFromVscodeMarketplace {
    publisher = "wingrunr21";
    name = "vscode-ruby";
    version = "0.28.0";
    sha256 = "1gab5cka87zw7i324rz9gmv423rf5sylsq1q1dhfkizmrpwzaxqz";
  })
  (extensionFromVscodeMarketplace {
    publisher = "wix";
    name = "glean";
    version = "5.2.2";
    sha256 = "0zicmdhphsyvbqsbabydfsr3gljmzjdixxqjk77qrfwjd2mzjh16";
  })
  (extensionFromVscodeMarketplace {
    publisher = "xabikos";
    name = "JavaScriptSnippets";
    version = "1.8.0";
    sha256 = "19xg24alxsvq8pvafprshg7qxzx8p37bzk7qz6kjgkpvandrdpl6";
  })
]
