# This file was auto-generated by: "generate_market_extensions".
{ extensionFromVscodeMarketplace }: [
  (extensionFromVscodeMarketplace {
    publisher = "aaron-bond";
    name = "better-comments";
    version = "2.1.0";
    sha256 = "0kmmk6bpsdrvbb7dqf0d3annpg41n9g6ljzc1dh0akjzpbchdcwp";
  })
  (extensionFromVscodeMarketplace {
    publisher = "alygin";
    name = "vscode-tlaplus";
    version = "1.5.4";
    sha256 = "0mf98244z6wzb0vj6qdm3idgr2sr5086x7ss2khaxlrziif395dx";
  })
  (extensionFromVscodeMarketplace {
    publisher = "ArashSahebolamri";
    name = "alloy";
    version = "0.7.1";
    sha256 = "00qm8rg0bbkmrvwrx13v68ninn8d4dm57m1j5f5p8r0344wcbwdj";
  })
  (extensionFromVscodeMarketplace {
    publisher = "arrterian";
    name = "nix-env-selector";
    version = "1.0.7";
    sha256 = "0mralimyzhyp4x9q98x3ck64ifbjqdp8cxcami7clvdvkmf8hxhf";
  })
  (extensionFromVscodeMarketplace {
    publisher = "azemoh";
    name = "one-monokai";
    version = "0.5.0";
    sha256 = "1rqg3np6jc9lrl9xqq8iq74y4ag3wnj5c0zv9h9ljpk5xzp4rdva";
  })
  (extensionFromVscodeMarketplace {
    publisher = "cschlosser";
    name = "doxdocgen";
    version = "1.3.2";
    sha256 = "08dp9bqxsxxqw8pm1sryl14xrvicagqwlxi5cc1vmksjh30dmn1a";
  })
  (extensionFromVscodeMarketplace {
    publisher = "dongyuzhao";
    name = "alloy-vscode";
    version = "0.1.6";
    sha256 = "1yyckiyf7ki6f951xij8i22zwkhb9hxaix36558qjwivqs6330y1";
  })
  (extensionFromVscodeMarketplace {
    publisher = "dorzey";
    name = "vscode-sqlfluff";
    version = "0.0.5";
    sha256 = "14zyz4gjwvia1sl32zv758havjhgp8yz5xjcga7w3ix9kdm0irhs";
  })
  (extensionFromVscodeMarketplace {
    publisher = "exiasr";
    name = "hadolint";
    version = "1.1.0";
    sha256 = "11pf45fbq1rfxa68n8hy7z3iwi3sxfykla20d942wd7faymddk54";
  })
  (extensionFromVscodeMarketplace {
    publisher = "formulahendry";
    name = "terminal";
    version = "0.0.10";
    sha256 = "0gj71xy7r82n1pic00xsi04dg7zg0dsxx000s03iq6lnz47s84gn";
  })
  (extensionFromVscodeMarketplace {
    publisher = "fwcd";
    name = "kotlin";
    version = "0.2.23";
    sha256 = "0r2flxawrfjx5ijn7wc7dva14hdxvqj7vrwr1dk7cak96yn51a4w";
  })
  (extensionFromVscodeMarketplace {
    publisher = "hashicorp";
    name = "terraform";
    version = "2.19.0";
    sha256 = "0imyddsk2hv68xqasbj1mprp66rpzarlmbq8jcqksbw4kc8drxwk";
  })
  (extensionFromVscodeMarketplace {
    publisher = "humao";
    name = "rest-client";
    version = "0.24.6";
    sha256 = "196pm7gv0488bpv1lklh8hpwmdqc4yimz389gad6nsna368m4m43";
  })
  (extensionFromVscodeMarketplace {
    publisher = "jcanero";
    name = "hoogle-vscode";
    version = "0.0.7";
    sha256 = "0ndapfrv3j82792hws7b3zki76m2s1bfh9dss1xjgcal1aqajka1";
  })
  (extensionFromVscodeMarketplace {
    publisher = "jebbs";
    name = "plantuml";
    version = "2.17.2";
    sha256 = "0yxnfq34g563w96dwfirqscjfclhzr48yb9cwfjjf0c0l638x9vv";
  })
  (extensionFromVscodeMarketplace {
    publisher = "jnoortheen";
    name = "nix-ide";
    version = "0.1.19";
    sha256 = "1ms96ij6z4bysdhqgdaxx2znvczyhzx57iifbqws50m1c3m7pkx7";
  })
  (extensionFromVscodeMarketplace {
    publisher = "joaompinto";
    name = "vscode-graphviz";
    version = "0.0.6";
    sha256 = "17z5zgr8l94mj8dgqxwsrpixnkz0778fp1g4rxc7i56wb1zbik3w";
  })
  (extensionFromVscodeMarketplace {
    publisher = "leanprover";
    name = "lean4";
    version = "0.0.68";
    sha256 = "1n7z4mj7dqw58dbnhm0pfzdncsb57sal1f54qp5aywjsbb4wspn5";
  })
  (extensionFromVscodeMarketplace {
    publisher = "lucax88x";
    name = "codeacejumper";
    version = "3.3.2";
    sha256 = "02a5f0lg0rmrjjf52z30mk19ii71pcdxjmbcb4v6haw1pkm6anqn";
  })
  (extensionFromVscodeMarketplace {
    publisher = "mads-hartmann";
    name = "bash-ide-vscode";
    version = "1.11.0";
    sha256 = "1hq41fy2v1grjrw77mbs9k6ps6gncwlydm03ipawjnsinxc9rdkp";
  })
  (extensionFromVscodeMarketplace {
    publisher = "mattn";
    name = "lisp";
    version = "0.1.12";
    sha256 = "0k10d77ffl6ybmk7mrpmlsawzwppp87aix2a2i24jq7lqnnqb9n7";
  })
  (extensionFromVscodeMarketplace {
    publisher = "maximedenes";
    name = "vscoq";
    version = "0.3.6";
    sha256 = "1sailpizg7zvncggdma9dyxdnga8jya1a2vswwij1rzd9il04j3g";
  })
  (extensionFromVscodeMarketplace {
    publisher = "meraymond";
    name = "idris-vscode";
    version = "0.0.12";
    sha256 = "1qvp5915gm9cx8143mn2xlnh4zbs87dscj7jrwb7b6ik93ja6vg3";
  })
  (extensionFromVscodeMarketplace {
    publisher = "ms-vscode";
    name = "cmake-tools";
    version = "1.9.2";
    sha256 = "12r360fr38qq1cvssg0ajhhipcaymbdjjd9dncy4fb02ajha823s";
  })
  (extensionFromVscodeMarketplace {
    publisher = "ms-vscode";
    name = "makefile-tools";
    version = "0.3.1";
    sha256 = "0xsawwqvp2rhgz6cx587ygjb3ggysilnwba2xpfialj1czl2984q";
  })
  (extensionFromVscodeMarketplace {
    publisher = "ms-vscode";
    name = "test-adapter-converter";
    version = "0.1.5";
    sha256 = "11x29njy746mjbv58s7cis2fj6xnmjqc0vn3nb4vv53skxcbhn4y";
  })
  (extensionFromVscodeMarketplace {
    publisher = "mtxr";
    name = "sqltools";
    version = "0.23.0";
    sha256 = "0gkm1m7jss25y2p2h6acm8awbchyrsqfhmbg70jaafr1dfxkzfir";
  })
  (extensionFromVscodeMarketplace {
    publisher = "mtxr";
    name = "sqltools-driver-mysql";
    version = "0.2.0";
    sha256 = "0l3apg0ickfj9j3qgr4fgvki1p0x4jrwvalp1id8fyzyskv5qlxw";
  })
  (extensionFromVscodeMarketplace {
    publisher = "mtxr";
    name = "sqltools-driver-pg";
    version = "0.2.0";
    sha256 = "0ws17sna87rs4ihcdj5lzxf8g2nkcgyjpqlafl5kii2c8x364y6j";
  })
  (extensionFromVscodeMarketplace {
    publisher = "naco-siren";
    name = "gradle-language";
    version = "0.2.3";
    sha256 = "15lzxvym0mkljjn57av1p4z6hqqwbsbn5idw2fn7nccgrl93aywf";
  })
  (extensionFromVscodeMarketplace {
    publisher = "nicoespeon";
    name = "abracadabra";
    version = "6.10.0";
    sha256 = "0pfcmkip5q7hffw1vjbrk1z1h8c0lq0dhqmh164s015jq9a8pdyh";
  })
  (extensionFromVscodeMarketplace {
    publisher = "notskm";
    name = "clang-tidy";
    version = "0.5.1";
    sha256 = "0z44hbrbzlhxbzf1j55xpl5fb7gic9avvcz4dvljrwz4qqdjzq4x";
  })
  (extensionFromVscodeMarketplace {
    publisher = "pivotal";
    name = "vscode-spring-boot";
    version = "1.31.0";
    sha256 = "18flcpf5xv33s54iivmpb67vf07i4pcwrqvaqa270sflv3igfyw3";
  })
  (extensionFromVscodeMarketplace {
    publisher = "redhat";
    name = "vscode-xml";
    version = "0.19.1";
    sha256 = "0k4lym09wbyz25q76db5awgdamx3ycpmjv5njvbi9b7damj0w99z";
  })
  (extensionFromVscodeMarketplace {
    publisher = "ritwickdey";
    name = "LiveServer";
    version = "5.7.4";
    sha256 = "18xggd12fq6yyfd5827c0a73j4mq8fd7npbv3ycdf9cr3gbgljby";
  })
  (extensionFromVscodeMarketplace {
    publisher = "Rubymaniac";
    name = "vscode-direnv";
    version = "0.0.2";
    sha256 = "1gml41bc77qlydnvk1rkaiv95rwprzqgj895kxllqy4ps8ly6nsd";
  })
  (extensionFromVscodeMarketplace {
    publisher = "ryanolsonx";
    name = "zenburn";
    version = "1.0.1";
    sha256 = "1gb159fkvadsnx5gb3l8pps9sa5xjcaqqiym952ar0yfhpfd0ziz";
  })
  (extensionFromVscodeMarketplace {
    publisher = "sjhuangx";
    name = "vscode-scheme";
    version = "0.4.0";
    sha256 = "07vjfymvfv98s5r5a4b5iqhgfz1wpgq2l8h3wlq1bnhhhvmq5pq4";
  })
  (extensionFromVscodeMarketplace {
    publisher = "twxs";
    name = "cmake";
    version = "0.0.17";
    sha256 = "11hzjd0gxkq37689rrr2aszxng5l9fwpgs9nnglq3zhfa1msyn08";
  })
  (extensionFromVscodeMarketplace {
    publisher = "vscjava";
    name = "vscode-java-debug";
    version = "0.38.0";
    sha256 = "1r5j7gqrr8yx2dm2qsq269bvmzm48acczas57r67wr6zmqfll375";
  })
  (extensionFromVscodeMarketplace {
    publisher = "vscjava";
    name = "vscode-java-test";
    version = "0.34.0";
    sha256 = "049fn36mhwdgkp11srym1lhvhrwil5lv3b9vg3chbgsd4sd1rszf";
  })
  (extensionFromVscodeMarketplace {
    publisher = "vscjava";
    name = "vscode-spring-boot-dashboard";
    version = "0.2.0";
    sha256 = "0m08v48p6554a1g7ynpzv1v0a6p5adaac95s8i07vp7y117g85a3";
  })
  (extensionFromVscodeMarketplace {
    publisher = "vscjava";
    name = "vscode-spring-initializr";
    version = "0.8.0";
    sha256 = "0x7dmss5jxz5iy6yhbzv8d6a19y061fnh5cwg01vgzgavv0hvjfi";
  })
  (extensionFromVscodeMarketplace {
    publisher = "wayou";
    name = "vscode-todo-highlight";
    version = "1.0.5";
    sha256 = "1sg4zbr1jgj9adsj3rik5flcn6cbr4k2pzxi446rfzbzvcqns189";
  })
  (extensionFromVscodeMarketplace {
    publisher = "wix";
    name = "glean";
    version = "5.2.2";
    sha256 = "0zicmdhphsyvbqsbabydfsr3gljmzjdixxqjk77qrfwjd2mzjh16";
  })
  (extensionFromVscodeMarketplace {
    publisher = "xabikos";
    name = "JavaScriptSnippets";
    version = "1.8.0";
    sha256 = "19xg24alxsvq8pvafprshg7qxzx8p37bzk7qz6kjgkpvandrdpl6";
  })
  (extensionFromVscodeMarketplace {
    publisher = "zxh404";
    name = "vscode-proto3";
    version = "0.5.5";
    sha256 = "08gjq2ww7pjr3ck9pyp5kdr0q6hxxjy3gg87aklplbc9bkfb0vqj";
  })
]
