# This file was auto-generated by: "generate_market_extensions".
{ extensionFromVscodeMarketplace }: [
  (extensionFromVscodeMarketplace {
    publisher = "aaron-bond";
    name = "better-comments";
    version = "2.1.0";
    sha256 = "0kmmk6bpsdrvbb7dqf0d3annpg41n9g6ljzc1dh0akjzpbchdcwp";
  })
  (extensionFromVscodeMarketplace {
    publisher = "arrterian";
    name = "nix-env-selector";
    version = "1.0.7";
    sha256 = "0mralimyzhyp4x9q98x3ck64ifbjqdp8cxcami7clvdvkmf8hxhf";
  })
  (extensionFromVscodeMarketplace {
    publisher = "azemoh";
    name = "one-monokai";
    version = "0.5.0";
    sha256 = "1rqg3np6jc9lrl9xqq8iq74y4ag3wnj5c0zv9h9ljpk5xzp4rdva";
  })
  (extensionFromVscodeMarketplace {
    publisher = "cschlosser";
    name = "doxdocgen";
    version = "1.3.2";
    sha256 = "08dp9bqxsxxqw8pm1sryl14xrvicagqwlxi5cc1vmksjh30dmn1a";
  })
  (extensionFromVscodeMarketplace {
    publisher = "dorzey";
    name = "vscode-sqlfluff";
    version = "0.0.5";
    sha256 = "14zyz4gjwvia1sl32zv758havjhgp8yz5xjcga7w3ix9kdm0irhs";
  })
  (extensionFromVscodeMarketplace {
    publisher = "exiasr";
    name = "hadolint";
    version = "1.1.0";
    sha256 = "11pf45fbq1rfxa68n8hy7z3iwi3sxfykla20d942wd7faymddk54";
  })
  (extensionFromVscodeMarketplace {
    publisher = "formulahendry";
    name = "terminal";
    version = "0.0.10";
    sha256 = "0gj71xy7r82n1pic00xsi04dg7zg0dsxx000s03iq6lnz47s84gn";
  })
  (extensionFromVscodeMarketplace {
    publisher = "humao";
    name = "rest-client";
    version = "0.24.5";
    sha256 = "1hj294nsmlzvhbvwv4wyf7mgfw64q4pgkjzzgyjfc26pzyaxb4bn";
  })
  (extensionFromVscodeMarketplace {
    publisher = "jcanero";
    name = "hoogle-vscode";
    version = "0.0.7";
    sha256 = "0ndapfrv3j82792hws7b3zki76m2s1bfh9dss1xjgcal1aqajka1";
  })
  (extensionFromVscodeMarketplace {
    publisher = "jebbs";
    name = "plantuml";
    version = "2.16.0";
    sha256 = "13vy0wnvx509kq92alad40s7gb68x68x19v2ah8k0mgk04dp6vqk";
  })
  (extensionFromVscodeMarketplace {
    publisher = "jnoortheen";
    name = "nix-ide";
    version = "0.1.18";
    sha256 = "1v3j67j8bydyqba20b2wzsfximjnbhknk260zkc0fid1xzzb2sbn";
  })
  (extensionFromVscodeMarketplace {
    publisher = "joaompinto";
    name = "vscode-graphviz";
    version = "0.0.6";
    sha256 = "17z5zgr8l94mj8dgqxwsrpixnkz0778fp1g4rxc7i56wb1zbik3w";
  })
  (extensionFromVscodeMarketplace {
    publisher = "jroesch";
    name = "lean";
    version = "0.16.39";
    sha256 = "0v1w0rmx2z7q6lfrl430fl6aq6n70y14s2fqsp734igdkdhdnvmk";
  })
  (extensionFromVscodeMarketplace {
    publisher = "lucax88x";
    name = "codeacejumper";
    version = "3.3.2";
    sha256 = "02a5f0lg0rmrjjf52z30mk19ii71pcdxjmbcb4v6haw1pkm6anqn";
  })
  (extensionFromVscodeMarketplace {
    publisher = "mads-hartmann";
    name = "bash-ide-vscode";
    version = "1.11.0";
    sha256 = "1hq41fy2v1grjrw77mbs9k6ps6gncwlydm03ipawjnsinxc9rdkp";
  })
  (extensionFromVscodeMarketplace {
    publisher = "mattn";
    name = "lisp";
    version = "0.1.11";
    sha256 = "1is81gmik2lc4wkil682lc34p1qcymb6xfwc942ig1msd33qv1g3";
  })
  (extensionFromVscodeMarketplace {
    publisher = "maximedenes";
    name = "vscoq";
    version = "0.3.5";
    sha256 = "05w4d4cr40xsr0pkry1cg3p5q2ji3dqld0p560grhrjlq27clj4r";
  })
  (extensionFromVscodeMarketplace {
    publisher = "meraymond";
    name = "idris-vscode";
    version = "0.0.11";
    sha256 = "0dfvrqvfpx34fwc87cbr5kq2cc4w5mdccwvwl2kmlrys1j4gjp0q";
  })
  (extensionFromVscodeMarketplace {
    publisher = "ms-kubernetes-tools";
    name = "vscode-kubernetes-tools";
    version = "1.3.3";
    sha256 = "1w22wyqszizcmr6qw0d5hqg64455yphzjjq6w13izc2flpird1kl";
  })
  (extensionFromVscodeMarketplace {
    publisher = "ms-vscode";
    name = "cmake-tools";
    version = "1.9.1";
    sha256 = "1r6wrqpcm2l74x25aa83aihy8hz86civgrs4j2rdx0y1pkvl61s3";
  })
  (extensionFromVscodeMarketplace {
    publisher = "ms-vscode";
    name = "makefile-tools";
    version = "0.2.2";
    sha256 = "05bnjikk0r7ix9sdd0w0rs543wzl46951z7gxrj378r0hjjwww3z";
  })
  (extensionFromVscodeMarketplace {
    publisher = "mtxr";
    name = "sqltools";
    version = "0.23.0";
    sha256 = "0gkm1m7jss25y2p2h6acm8awbchyrsqfhmbg70jaafr1dfxkzfir";
  })
  (extensionFromVscodeMarketplace {
    publisher = "mtxr";
    name = "sqltools-driver-mysql";
    version = "0.2.0";
    sha256 = "0l3apg0ickfj9j3qgr4fgvki1p0x4jrwvalp1id8fyzyskv5qlxw";
  })
  (extensionFromVscodeMarketplace {
    publisher = "mtxr";
    name = "sqltools-driver-pg";
    version = "0.2.0";
    sha256 = "0ws17sna87rs4ihcdj5lzxf8g2nkcgyjpqlafl5kii2c8x364y6j";
  })
  (extensionFromVscodeMarketplace {
    publisher = "naco-siren";
    name = "gradle-language";
    version = "0.2.3";
    sha256 = "15lzxvym0mkljjn57av1p4z6hqqwbsbn5idw2fn7nccgrl93aywf";
  })
  (extensionFromVscodeMarketplace {
    publisher = "nicoespeon";
    name = "abracadabra";
    version = "6.6.0";
    sha256 = "0324p7a2swpd4r47xfna1134s3xzpdggws39zwm99zqsijz7mjkj";
  })
  (extensionFromVscodeMarketplace {
    publisher = "notskm";
    name = "clang-tidy";
    version = "0.5.1";
    sha256 = "0z44hbrbzlhxbzf1j55xpl5fb7gic9avvcz4dvljrwz4qqdjzq4x";
  })
  (extensionFromVscodeMarketplace {
    publisher = "ocamllabs";
    name = "ocaml-platform";
    version = "1.8.4";
    sha256 = "0lz9dgldd6q9xsl3f3n27iv752kwrn6ca0nimmxq1gqcwq19hmsg";
  })
  (extensionFromVscodeMarketplace {
    publisher = "redhat";
    name = "vscode-xml";
    version = "0.18.0";
    sha256 = "03igpqq8j6qbnr2z7bsg1sj4lvd38s2b59rgc2g714pgj3m80wd4";
  })
  (extensionFromVscodeMarketplace {
    publisher = "ritwickdey";
    name = "LiveServer";
    version = "5.6.1";
    sha256 = "077arf3hsn1yb8xdhlrax5gf93ljww78irv4gm8ffmsqvcr1kws0";
  })
  (extensionFromVscodeMarketplace {
    publisher = "Rubymaniac";
    name = "vscode-direnv";
    version = "0.0.2";
    sha256 = "1gml41bc77qlydnvk1rkaiv95rwprzqgj895kxllqy4ps8ly6nsd";
  })
  (extensionFromVscodeMarketplace {
    publisher = "ryanolsonx";
    name = "zenburn";
    version = "1.0.1";
    sha256 = "1gb159fkvadsnx5gb3l8pps9sa5xjcaqqiym952ar0yfhpfd0ziz";
  })
  (extensionFromVscodeMarketplace {
    publisher = "sjhuangx";
    name = "vscode-scheme";
    version = "0.4.0";
    sha256 = "07vjfymvfv98s5r5a4b5iqhgfz1wpgq2l8h3wlq1bnhhhvmq5pq4";
  })
  (extensionFromVscodeMarketplace {
    publisher = "twxs";
    name = "cmake";
    version = "0.0.17";
    sha256 = "11hzjd0gxkq37689rrr2aszxng5l9fwpgs9nnglq3zhfa1msyn08";
  })
  (extensionFromVscodeMarketplace {
    publisher = "vscjava";
    name = "vscode-java-debug";
    version = "0.36.0";
    sha256 = "1p9mymbf8sn39k44350zf3zwl29fhcwxfsqxr7841ch1qz88w9r8";
  })
  (extensionFromVscodeMarketplace {
    publisher = "vscjava";
    name = "vscode-java-test";
    version = "0.32.0";
    sha256 = "0lq6daz228ipzls88y09zbdsv9n6backs5bddpdam628rs99qvn3";
  })
  (extensionFromVscodeMarketplace {
    publisher = "xabikos";
    name = "JavaScriptSnippets";
    version = "1.8.0";
    sha256 = "19xg24alxsvq8pvafprshg7qxzx8p37bzk7qz6kjgkpvandrdpl6";
  })
  (extensionFromVscodeMarketplace {
    publisher = "zxh404";
    name = "vscode-proto3";
    version = "0.5.4";
    sha256 = "08dfl5h1k6s542qw5qx2czm1wb37ck9w2vpjz44kp2az352nmksb";
  })
]
