# This file was auto-generated by: "generate_market_extensions".
{ extensionFromVscodeMarketplace }: [
  (extensionFromVscodeMarketplace {
    publisher = "aaron-bond";
    name = "better-comments";
    version = "2.1.0";
    sha256 = "0kmmk6bpsdrvbb7dqf0d3annpg41n9g6ljzc1dh0akjzpbchdcwp";
  })
  (extensionFromVscodeMarketplace {
    publisher = "arrterian";
    name = "nix-env-selector";
    version = "1.0.7";
    sha256 = "0mralimyzhyp4x9q98x3ck64ifbjqdp8cxcami7clvdvkmf8hxhf";
  })
  (extensionFromVscodeMarketplace {
    publisher = "avli";
    name = "clojure";
    version = "0.13.1";
    sha256 = "1qh17lp7xpc9ggf5awya9d65wxxmr0z1cbpb2w6i63w0118iggx8";
  })
  (extensionFromVscodeMarketplace {
    publisher = "azemoh";
    name = "one-monokai";
    version = "0.5.0";
    sha256 = "1rqg3np6jc9lrl9xqq8iq74y4ag3wnj5c0zv9h9ljpk5xzp4rdva";
  })
  (extensionFromVscodeMarketplace {
    publisher = "cschlosser";
    name = "doxdocgen";
    version = "1.3.2";
    sha256 = "08dp9bqxsxxqw8pm1sryl14xrvicagqwlxi5cc1vmksjh30dmn1a";
  })
  (extensionFromVscodeMarketplace {
    publisher = "formulahendry";
    name = "terminal";
    version = "0.0.10";
    sha256 = "0gj71xy7r82n1pic00xsi04dg7zg0dsxx000s03iq6lnz47s84gn";
  })
  (extensionFromVscodeMarketplace {
    publisher = "humao";
    name = "rest-client";
    version = "0.24.5";
    sha256 = "1hj294nsmlzvhbvwv4wyf7mgfw64q4pgkjzzgyjfc26pzyaxb4bn";
  })
  (extensionFromVscodeMarketplace {
    publisher = "jcanero";
    name = "hoogle-vscode";
    version = "0.0.7";
    sha256 = "0ndapfrv3j82792hws7b3zki76m2s1bfh9dss1xjgcal1aqajka1";
  })
  (extensionFromVscodeMarketplace {
    publisher = "jroesch";
    name = "lean";
    version = "0.16.39";
    sha256 = "0v1w0rmx2z7q6lfrl430fl6aq6n70y14s2fqsp734igdkdhdnvmk";
  })
  (extensionFromVscodeMarketplace {
    publisher = "mads-hartmann";
    name = "bash-ide-vscode";
    version = "1.11.0";
    sha256 = "1hq41fy2v1grjrw77mbs9k6ps6gncwlydm03ipawjnsinxc9rdkp";
  })
  (extensionFromVscodeMarketplace {
    publisher = "mattn";
    name = "lisp";
    version = "0.1.11";
    sha256 = "1is81gmik2lc4wkil682lc34p1qcymb6xfwc942ig1msd33qv1g3";
  })
  (extensionFromVscodeMarketplace {
    publisher = "maximedenes";
    name = "vscoq";
    version = "0.3.5";
    sha256 = "05w4d4cr40xsr0pkry1cg3p5q2ji3dqld0p560grhrjlq27clj4r";
  })
  (extensionFromVscodeMarketplace {
    publisher = "meraymond";
    name = "idris-vscode";
    version = "0.0.10";
    sha256 = "15sq8g16bxmw6wzacz757nkkpqr03gsxxj4ig3fpr8blzf6v2bd0";
  })
  (extensionFromVscodeMarketplace {
    publisher = "ms-kubernetes-tools";
    name = "vscode-kubernetes-tools";
    version = "1.3.3";
    sha256 = "1w22wyqszizcmr6qw0d5hqg64455yphzjjq6w13izc2flpird1kl";
  })
  (extensionFromVscodeMarketplace {
    publisher = "ms-vscode";
    name = "cmake-tools";
    version = "1.8.1";
    sha256 = "0k1m9k3cjjflpz75gjicsb59r1c4mnld9aps5rnyqa154a6mwnkl";
  })
  (extensionFromVscodeMarketplace {
    publisher = "ms-vscode";
    name = "makefile-tools";
    version = "0.2.2";
    sha256 = "05bnjikk0r7ix9sdd0w0rs543wzl46951z7gxrj378r0hjjwww3z";
  })
  (extensionFromVscodeMarketplace {
    publisher = "notskm";
    name = "clang-tidy";
    version = "0.5.1";
    sha256 = "0z44hbrbzlhxbzf1j55xpl5fb7gic9avvcz4dvljrwz4qqdjzq4x";
  })
  (extensionFromVscodeMarketplace {
    publisher = "ocamllabs";
    name = "ocaml-platform";
    version = "1.8.4";
    sha256 = "0lz9dgldd6q9xsl3f3n27iv752kwrn6ca0nimmxq1gqcwq19hmsg";
  })
  (extensionFromVscodeMarketplace {
    publisher = "Rubymaniac";
    name = "vscode-direnv";
    version = "0.0.2";
    sha256 = "1gml41bc77qlydnvk1rkaiv95rwprzqgj895kxllqy4ps8ly6nsd";
  })
  (extensionFromVscodeMarketplace {
    publisher = "ryanolsonx";
    name = "zenburn";
    version = "1.0.1";
    sha256 = "1gb159fkvadsnx5gb3l8pps9sa5xjcaqqiym952ar0yfhpfd0ziz";
  })
  (extensionFromVscodeMarketplace {
    publisher = "sjhuangx";
    name = "vscode-scheme";
    version = "0.4.0";
    sha256 = "07vjfymvfv98s5r5a4b5iqhgfz1wpgq2l8h3wlq1bnhhhvmq5pq4";
  })
  (extensionFromVscodeMarketplace {
    publisher = "twxs";
    name = "cmake";
    version = "0.0.17";
    sha256 = "11hzjd0gxkq37689rrr2aszxng5l9fwpgs9nnglq3zhfa1msyn08";
  })
]
