#!/bin/bash

# Install VSCode with extensions.

set -eu

BASE_DIR="${PWD}"

DOWNLOAD_DIR="/tmp/vscode-$(date +%s)"

IN_VSCODE_DIR="${BASE_DIR}/scripts/include/vscode"
IN_EXTENSIONS_FILENAME="${IN_VSCODE_DIR}/extensions.txt"
IN_SETTINGS_FILENAME="${IN_VSCODE_DIR}/settings.json"
IN_KEYBINDINGS_FILENAME="${IN_VSCODE_DIR}/keybindings.json"

base_config_dir() {
    unameOut="$(uname -s)"
    case "${unameOut}" in
    Linux*) echo "$HOME/.config" ;;
    Darwin*) echo "$HOME/Library/Application Support" ;;
    *) exit 69 ;;
    esac
}

install_editor_deb() {
    local download_filename="${DOWNLOAD_DIR}/code.deb"

    mkdir -p "${DOWNLOAD_DIR}"

    curl -L -o "${download_filename}" 'https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-x64'
    sudo dpkg -i "${download_filename}"

    mkdir -p "$(base_config_dir)/Code"
}

install_editor_macos() {
    local destination="/Applications/Visual Studio Code.app"

    local download_filename="${DOWNLOAD_DIR}/code.zip"

    mkdir -p "${DOWNLOAD_DIR}"

    curl -L -o "${download_filename}" 'https://code.visualstudio.com/sha/download?build=stable&os=darwin-universal'
    unzip -q "${download_filename}" -d "${DOWNLOAD_DIR}"

    mv -f "${DOWNLOAD_DIR}/Visual Studio Code.app" "${destination}"

    sudo ln -sf "${destination}/Contents/Resources/app/bin/code" "/usr/local/bin/code"

    mkdir -p "$(base_config_dir)/Code"

}

install_editor() {
    if ! command -v code; then
        unameOut="$(uname -s)"
        case "${unameOut}" in
        Linux*) install_editor_deb ;;
        Darwin*) install_editor_macos ;;
        *) exit 69 ;;
        esac
    fi
}

install_extensions() {
    cat "${IN_EXTENSIONS_FILENAME}" | grep '^#' | sed 's/^#//' | xargs -I{} code --uninstall-extension {} --force
    cat "${IN_EXTENSIONS_FILENAME}" | grep -v '^#' | xargs -I{} code --install-extension {} --force
}

install_config() {
    local target_dir="$(base_config_dir)/Code/User/"

    ln -sf "${IN_SETTINGS_FILENAME}" "${target_dir}"
    ln -sf "${IN_KEYBINDINGS_FILENAME}" "${target_dir}"
}

main() {
    install_editor
    install_extensions || true
    install_config
}

main
